-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 10:18:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tweeter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tweeter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweeter` DEFAULT CHARACTER SET utf8 ;
USE `tweeter` ;

-- -----------------------------------------------------
-- Table `tweeter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `birthdate` DATETIME NOT NULL,
  `country` VARCHAR(255) NULL,
  `password` TEXT NOT NULL,
  `bio` TEXT NULL,
  `avatar` VARCHAR(255) NULL,
  `banner` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`hashtag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(255) NOT NULL,
  `nbr_use` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`tweet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `like` INT NULL DEFAULT 0,
  `retweet` INT NULL DEFAULT 0,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tweet_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`followers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `follower` INT NOT NULL,
  `folllowing` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_followers_users1`
    FOREIGN KEY (`follower`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_followers_users2`
    FOREIGN KEY (`folllowing`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`private_msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`private_msg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `sender` INT NOT NULL,
  `receiver` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_private_msg_users1`
    FOREIGN KEY (`receiver`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_private_msg_users2`
    FOREIGN KEY (`sender`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT(255) NOT NULL,
  `tweet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_tweet1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweeter`.`tweet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`tweet_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`tweet_like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tweet_like_tweet1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweeter`.`tweet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tweet_like_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweeter`.`retweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter`.`retweet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_retweet_tweet1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `tweeter`.`tweet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retweet_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `tweeter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
